### ISSUE TITLE
Little bug and Ideas for 0.5

### ISSUE THREAD

**Issue by CloudeLecaw** [Vastrix/Offline-Teleporter#1]
Hiho first let me thank you for doing this great plugin! :)

Found little Bugs:
Since Spigot 1.8.3 the plugin sometime saves the file of the player in the main Minecraftfolder instead of the plugindatdafolder :3

Ideas:
Changeing from names to uuids :3 this maybe better since player can change their names.
(1.8 and above)

**Comment by Vastrix** [comment]
We'll look into it! Thanks for reporting it :)

The latest version already uses uuid's instead of names tho, If a player changes his name, his file will be updated as soon as he logs in! ;)

**Comment by Vastrix** [comment]
I'm assuming the bug occurs to new players joining?

**Comment by Vastrix** [comment]
Hmm, I can't actually find anything in the source that might be causing this :s 

Any chance you can provide me with the following info:
- How often does it happen?
- Does it only happen under certain circumstances if so, which?
- Is there an error shown in the console/logs?

**Comment by RoboMWM** [comment]
I've actually seen this happen - it seems to happen with new players. I can't really determine why or when it happens.
